dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=remotia setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: KOAOQWNaUuiUeA+DhJr9h0og1peGxTzGgff+dZdg9f+QBbnIlLTRUBSvDTDBIRuSMN0bHf6/YCN6VvUMTUY3/JSDqD11PlPcBKF3R9vRQAUQZ52SFd/p1La6Ad58QcEjSl9t0WmlYrQvjf6AizIZNtXcL2AhoOpWsjYTQhLn84C+48pmyDlrST4awBxHgVCAYIFUazV08/WmpyEZrd6ZLw0ZtzjSqBKjZA1xKLZwkZJPSwMuYlyjpvZbjkx+rp88HkBEb3rMxuTvJiIlXqmMjAL8TVY36l0X6Gzh+hiHWllU4yN1RBeGCSoanWZWsrCJo1Vwrw6p3jE8fgQ5Q/6KU/2kAzo+jz1PiHonBoDE2Dz8rXb9w4khbehAwBAzW7ti5WeRWCFLq22YGfD8ShHNyKHvuhc7V1UkB2hQcJ0DeWLj7CwLwDhARBR+7vyrzylT2y8qdsybvKc0tu47FdT+BFtlQqRM4CFgOQrPo0wBR+pogROJUayHsYfe0sbKHsq5wsWRCYX0QXBTkkQmMdn7iBJ5Q2ZynZuFTQR2BYhoCylzFQVvYa1PLGVDkNr6e+evMMjXelLf9cRMA0PV4yTbJlT6PKR48A3vZkI7Iuq4F7mZiN9AF5lg6SKOHF/eAZCDa+ERPOOqxbXGz9/n3gOeB6svcvB0CMdl8NhwA5XGWvE=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
