sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]];  then pip install --upgrade "pip<10.0" "setuptools<30.0"; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=remotia setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: HHIi6RAQeG0WzQBIir9Pkk7rnIFEZXiO5QgBvMnbmE+4cxdT/9sXzqSZqDOsw9EeznM6/bs2PB63HO1nuqaI/FnWJm0pzFmviFfOby9PPvwsHWkpdSwJndP03BZ+cYQstNCLLT40slteOTMhkPT6HNE/6H88tRXnzwg633WfizF76s0mAGUbtUOwaKHrixs3F4T4ziY9k9dhZkqXjaOhQO6noImXveteKLocpPuBX7T37vzMZXxrNkgiXDFyeDK5SeLWsV0OxqX5q8V3SsJufuC2TYxGnOQE8WNwjnpImac8+DoX/PNgQUiKCi4/Ew+1huYGH3FgFcwSO/Qdfip03zw3KmXzFFAFT63sH8klGBCnwwE6F73QRxCjk1eOR3L5ogV7HvNTAagA+V1HH7o2b2XEwrPWipmS5Ka5ByD+URk8aaZN+soAd4OzxAxCc3wjaCb1bRK9hug8OR0Y288+DKWfZ9PWRk0w44jXrZuC7DEyHB2EO3oiUeMyhHMHTW45v3VQY0jenJvooMe9Ky+Qgl3D8Pt9xSotvc9dN2YHguQQrearay/AlUEGVwUorpTFnJiHb++yG9i5hIujPo0jILPUDKs0PnfiVvVK1w2vzzaSCvVzsPeTiELNfsuJzirhMFl/c4fIEX78AC4pURTIj+Zauv2W4hFBHlwFJp1hxwk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
